package constants;

public class UIConstants {

	public static final String TITLE = "title";
	public static final String DEFAULT_RESOURCE = "references/";
	public static final String SCREEN_LANG = "Words";
	public static final String SPLASH_CSS = "splash.css";
	public static final String DEMO_CSS = "demo.css";
	public static final String GO = "go";
	public static final String RSRC_LANG = "resources/languages/";
	public static final String SYNTAX = "Syntax";
	public static final String EXTRAS = "Extras";
	public static final String ERRORS = "Errors";
	public static final double WIDTH = 1300;
	public static final double HEIGHT = 750;
	public static final double TURTLE_IMAGE_WIDTH = 50;
	public static final double TURTLE_IMAGE_HEIGHT = 50;
	public static final double SWIDTH = 500;
	public static final double SHEIGHT = 500;
	public static final double RECT_W = 600;
	public static final double CANVAS_SIZE = 475;
	public static final double BORDER_WIDTH = 25;
	public static final double METHODS_Y = 35; 
	public static final double INITIAL_X = 385;
	public static final double INITIAL_Y = 0;
	public static final double INITIAL_HEADING = 90;
	public static final double LOWER_PANE_WIDTH = 450;
	public static final double LOWER_PANE_HEIGHT = 200;
	public static final double UPPER_PANE_WIDTH = 360;
	public static final double UPPER_PANE_HEIGHT = 475;
	public static final double COORDINATE_LOCATION_X = 450;
	public static final double COORDINATE_LOCATION_Y = 500;
	public static final double VARIABLE_PANE_X = 100;
	public static final double COLOR_SELECTOR_WIDTH = 100;
	public static final double BACKGROUND_PICK_X = 100;
	public static final double PEN_PICK_X = 250;
	public static final double LOWER_PANE_Y = 525;
	public static final double HISTORY_PANE_X = 900;
	public static final double IMAGE_SELECT_X = 400;
	public static final double IMAGE_SELECT_WIDTH = 100;
	public static final double CANVAS_X = 410;
	public static final double ROTATION = -90;
	public static final double NINETY = 90;
	public static final double ZERO = 0;
	public static final double RECT_X = 200;
	public static final double ARC = 20;
	public static final double BUTTON_Y = 250;
	public static final double BUTTON_H = 50;
	public static final double TURTLE_PANE_X = 300;
	public static final double TURTLE_MIN_W = 250;
	public static final double USER_X = 50;
	public static final double TURTLE_SIZE = 50;
	public static final double GO_BUTTON_Y = 355;
	public static final double LOAD_BUTTON_Y = 300;
	public static final double WEL_RECT_X = 110;
	public static final double PADDING = 4;
	public static final double RECTANGLE_W = 80;
	public static final double RECTANGLE_H = 18;
	public static final double TWO = 2;
	public static final double MAX_PANE = 400;
	
	
	public static final String CHIN = "CHIN";
	public static final String ENG = "ENG";
	public static final String FRA = "FRA";
	public static final String GER = "GER";
	public static final String ITA = "ITA";
	public static final String POR = "POR";
	public static final String RUS = "RUS";
	public static final String SPA = "SPA";
	public static final String SYN = "SYN";
}
